# Generated by Django 5.0.3 on 2024-04-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chef',
            table='Chefs',
        ),
        migrations.AlterModelTable(
            name='ingredient',
            table='Ingerients',
        ),
        migrations.AlterModelTable(
            name='rating',
            table='Ratings',
        ),
    ]
